#############################################################################
# Makefile for building: Pro4
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue Apr 24 16:35:07 2012
# Project:  Pro4.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile Pro4.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = addscore.cpp \
		bullet.cpp \
		controller.cpp \
		enemy.cpp \
		enemybullet.cpp \
		enemyshot.cpp \
		gates.cpp \
		lv1background.cpp \
		main.cpp \
		planets.cpp \
		power.cpp \
		shark.cpp \
		shotenemy.cpp \
		star.cpp \
		sun.cpp \
		you.cpp 
OBJECTS       = addscore.o \
		bullet.o \
		controller.o \
		enemy.o \
		enemybullet.o \
		enemyshot.o \
		gates.o \
		lv1background.o \
		main.o \
		planets.o \
		power.o \
		shark.o \
		shotenemy.o \
		star.o \
		sun.o \
		you.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Pro4.pro
QMAKE_TARGET  = Pro4
DESTDIR       = 
TARGET        = Pro4

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Pro4.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile Pro4.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Pro4.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Pro41.0.0 || $(MKDIR) .tmp/Pro41.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Pro41.0.0/ && $(COPY_FILE) --parents addscore.h bullet.h controller.h enemy.h enemybullet.h enemyshot.h gates.h lv1background.h planets.h power.h shark.h shotenemy.h star.h sun.h you.h .tmp/Pro41.0.0/ && $(COPY_FILE) --parents addscore.cpp bullet.cpp controller.cpp enemy.cpp enemybullet.cpp enemyshot.cpp gates.cpp lv1background.cpp main.cpp planets.cpp power.cpp shark.cpp shotenemy.cpp star.cpp sun.cpp you.cpp .tmp/Pro41.0.0/ && (cd `dirname .tmp/Pro41.0.0` && $(TAR) Pro41.0.0.tar Pro41.0.0 && $(COMPRESS) Pro41.0.0.tar) && $(MOVE) `dirname .tmp/Pro41.0.0`/Pro41.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Pro41.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

addscore.o: addscore.cpp addscore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addscore.o addscore.cpp

bullet.o: bullet.cpp bullet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bullet.o bullet.cpp

controller.o: controller.cpp controller.h \
		star.h \
		planets.h \
		lv1background.h \
		sun.h \
		addscore.h \
		shark.h \
		power.h \
		enemy.h \
		enemyshot.h \
		shotenemy.h \
		enemybullet.h \
		bullet.h \
		gates.h \
		you.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o controller.cpp

enemy.o: enemy.cpp enemy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enemy.o enemy.cpp

enemybullet.o: enemybullet.cpp enemybullet.h \
		bullet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enemybullet.o enemybullet.cpp

enemyshot.o: enemyshot.cpp enemyshot.h \
		enemy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enemyshot.o enemyshot.cpp

gates.o: gates.cpp gates.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gates.o gates.cpp

lv1background.o: lv1background.cpp lv1background.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lv1background.o lv1background.cpp

main.o: main.cpp controller.h \
		star.h \
		planets.h \
		lv1background.h \
		sun.h \
		addscore.h \
		shark.h \
		power.h \
		enemy.h \
		enemyshot.h \
		shotenemy.h \
		enemybullet.h \
		bullet.h \
		gates.h \
		you.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

planets.o: planets.cpp planets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o planets.o planets.cpp

power.o: power.cpp power.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o power.o power.cpp

shark.o: shark.cpp shark.h \
		planets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shark.o shark.cpp

shotenemy.o: shotenemy.cpp shotenemy.h \
		enemy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shotenemy.o shotenemy.cpp

star.o: star.cpp star.h \
		planets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o star.o star.cpp

sun.o: sun.cpp sun.h \
		planets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sun.o sun.cpp

you.o: you.cpp you.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o you.o you.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

